### ISSUE TITLE
Title underline too short warning

### ISSUE THREAD

**Issue by uyar** [fschulze/lektor-rst#3]
If the rst text contains a title underlined with dashes that are as long as the title text, one of the dashes get removed and this causes a "title underline too short" warning.

**Comment by fschulze** [comment]
That is really weird, because I just call into docutils. I don't think your fix is correct then, because title underlines can be done with a lot more characters than just ``-``. I commonly use ``=`` and ``+``. There are also combinations possible. There must be some other reason this fails.

**Comment by uyar** [comment]
There is no problem with other symbols. I guess this comes from lektor, not docutils. Lektor uses triple dashes in its contents file and its documentation states that if you want to use this symbol you should add one more dash. Anyway, adding a dash doesn't harm because docutils says that the underline should be "at least as long as the title text".

**Comment by fschulze** [comment]
Ah, ok, then that makes more sense. Will look into it.
