### ISSUE TITLE
Issues with docutils generated HTML

### ISSUE THREAD

**Issue by uyar** [fschulze/lektor-rst#5]
The HTML code generated by docutils has some issues that make it harder to integrate it into CSS frameworks (I'm using it with [Bulma](https://bulma.io/)):

- `table` elements have `border` attributes (validator complains on this)
- `col` elements have `width` attributes (again, validator complaint)
- some table elements get `valign` attributes (validator complaint)
- containers get a `container` class (In Bulma this is a special class name)

Other than that, there are some unnecessary but possibly harmless issues:

- many elements get a `docutils` class
- `ul` elements get a `simple` class
- `th` elements get a `head` class

I'm thinking about implementing a filter called something like `cleanrst` that will optionally remove these extra attributes.

**Comment by fschulze** [comment]
I don't remember the details, but I think it's possible to do that during html generation in docutils and not by altering the HTML afterwards.

Do I understand it correctly, that the filter would be called via the lektor templates?

**Comment by uyar** [comment]
I didn't know that you can do it in docutils, that would better of course. Yes, I thought it could be lektor filter and it could be used like `{{ this.body|cleanrt }}`. The various cleaning operations could be parameters of the filter.

**Comment by fschulze** [comment]
Fixed via #11
