### ISSUE TITLE
Issue with python 3

### ISSUE THREAD

**Issue by johngi2013** [fschulze/lektor-rst#9]
I use python 3, and I could not get lektor-rst to work properly - the preview field and the final html were blank - until
I incorporated a change where lektor-rst.py appeared to be out of step with lektor/markdown.py
with regards to a python2/3 switch. ie the main lektor file contained this

    if not PY2:
        __str__ = __unicode__

**Comment by fschulze** [comment]
It seems like this was fixed in Lektor itself. I just added tests and it seems to work. Feel free to reopen if this is still an issue.
